name: Scheduled Ping

# Controls when the action will run. 
on:
  schedule:
  - cron: "30 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pinger_job:
    runs-on: ubuntu-latest
    name: Ping All Sites
    steps:
    - uses: actions/checkout@v2
    - name: Step 1 Check the site
      id: check_status
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://www.statsig.com"
        expected-statuses: "200,301"
    - name: Step 2 Get Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    - name: Step 3 Log status
      id: log_status
      run: echo ${{ steps.date.outputs.date }}, ${{ steps.check_status.outcome }} >> www_report.log
    - name: Step 4 Commit Log
      run: |
        git config --global user.name 'Vijaye Raji'
        git config --global user.email 'vijaye@statsig.com'
        git add -A
        git commit -am 'Status log - automated'
        git push
        
    
