name: Scheduled Ping

# Controls when the action will run. 
on:
  schedule:
  - cron: "*/30 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pinger_job:
    runs-on: ubuntu-latest
    name: Ping All Sites
    steps:
    - name: Step 1 Check the site
      id: check_status
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://www.statsig.com"
        expected-statuses: "200,301"
    - name: Step 2 Log status
      id: log_status
      run: echo ${{ step.check_status.outcome }}
    
